# Generated by Django 2.2.9 on 2020-01-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_product_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
